### ISSUE TITLE
Support Rust stable

### ISSUE THREAD

**Issue by ramn** [jfschaefer/rust-libxml#2]
Would be nice to use this library from Rust stable. The StaticMutex is a problem. Do you think something like this could work instead? https://github.com/ramn/rust-libxml/tree/replace_static_mutex

I can make a pull request if you think the approach is ok.

**Comment by dginev** [comment]
Hi @ramn , that sounds like a great idea.

If you already have the code written, feel free to file a PR for review. We should release on crates.io once the wrapper works with the stable Rust.

Btw @jfschaefer we should decide how to maintain the wrapper, and in which repo. We could also transfer it to the KWARC org, etc. The only thing to solve on that front is that the repo has an active maintainer at all times, so that it doesn't become stale.

**Comment by ramn** [comment]
Here is a PR: https://github.com/jfschaefer/rust-libxml/pull/3

**Comment by dginev** [comment]
Merged, thanks for contributing!

**Comment by ramn** [comment]
Np, thanks for providing this great library!
